
language: python
dist: xenial
sudo: false
matrix:
  include:
    - python: 3.6.8
      env: TOX_ENV=py36
    - python: 3.7.3
      env: TOX_ENV=py37
    - python: 3.7.3
      env: TOX_ENV=cover
    - python: 3.7.3
      env: TOX_ENV=style
    - python: 3.7.3
      env: TOX_ENV=docs

install:
  - pip install -U pip wheel
  - pip install tox
cache:
  directories:
    - $HOME/.cache/pip
before_script:
  - uname -a
script:
  - cd app
  - tox -v -e $TOX_ENV
