version: '3'
services:
  nginx:
    build: ./nginx/
    container_name: "legalist-test-devops-chintal-nginx"
    hostname: "legalist-test-devops-chintal-nginx"
    ports:
      - "1079:80"
    links:
      - app:legalist-test-devops-chintal-app
    depends_on:
      - app
  app:
    build: ./app/
    container_name: "legalist-test-devops-chintal-app"
    hostname: "legalist-test-devops-chintal-app"
    expose:
      - "8080"
    links:
      - redis:legalist-test-devops-chintal-redis
      - postgres:legalist-test-devops-chintal-postgres
    depends_on:
      - postgres
  redis:
    build: ./redis/
    container_name: "legalist-test-devops-chintal-redis"
    hostname: "legalist-test-devops-chintal-redis"
    expose:
      - "6379"
  postgres:
    build: ./postgres/
    container_name: "legalist-test-devops-chintal-postgres"
    hostname: "legalist-test-devops-chintal-postgres"
    expose:
      - "5432"
